// CV copy, in English and French. Kept in step with config/experience.ts and
// config/sideProjects.ts, which are the source of truth for the site.

export const content = {
  en: {
    lang: 'en',
    file: 'CV_EN_William_Guinaudie',
    title: 'William Guinaudie · CV',
    role: 'AI Engineer · Full-stack Developer',
    tagline:
      'I build products with AI agents, and the workflows that make those agents reliable. Agents do the legwork; I make the engineering calls, review the code and ship it.',
    facts: [
      ['Based in', 'Lausanne, Switzerland'],
      ['Nationality', 'British and French'],
      ['Work permit', 'Swiss work permit held'],
      ['Phone', '+33 6 35 94 82 91', 'tel:+33635948291'],
      ['Email', 'william.guinaudie@gmail.com', 'mailto:william.guinaudie@gmail.com'],
      ['Languages', 'English and French, both native'],
      ['Portfolio', 'williamguinaudie.com', 'https://www.williamguinaudie.com/?lang=en'],
      ['GitHub', 'github.com/NeoHuncho', 'https://github.com/NeoHuncho'],
      ['LinkedIn', 'linkedin.com/in/william-g-178156180', 'https://www.linkedin.com/in/william-g-178156180/'],
    ],
    site: 'https://www.williamguinaudie.com/?lang=en',
    qrCaption: 'The interactive version, with a playable mock of my agent board.',
    how: {
      eyebrow: 'How I work',
      title: 'Agents do the legwork. I make the calls.',
      me: 'Me',
      steps: [
        {
          name: 'Plan',
          who: 'Agents',
          body: 'Scheduled runs triage feedback and errors, or comb the code for security and performance wins. Each finding comes with a plan.',
        },
        { name: 'Decide', who: 'me', body: 'I accept, question or reject each plan.' },
        {
          name: 'Build',
          who: 'Agent + CI',
          body: 'An agent implements it on its own branch; CI checks it.',
        },
        { name: 'Ship', who: 'me', body: 'I review every pull request, then merge and ship.' },
      ],
    },
    sections: {
      experience: 'Experience',
      projects: 'Side projects',
      skills: 'Tools I use',
      education: 'Education',
      more: 'Also',
    },
    built: 'What I built',
    ai: 'How I used AI',
    experience: [
      {
        when: '03.2026 – now',
        length: 'Current role',
        city: 'Lausanne, CH',
        role: 'AI Engineer · Full-stack Developer',
        company: 'Apptitude',
        link: 'https://apptitude.ch/',
        sector: 'Digital agency',
        summary:
          'Client projects, mainly a Swiss financial-planning platform for wealth advisors, built front to back in an Nx monorepo.',
        stats: [
          ['110+', 'merged pull requests in 6 months'],
          ['Most', 'of the repo’s agent tooling, built by me'],
        ],
        built: [
          'Wealth and retirement simulation across the Swiss three-pillar system, with quick actions like a new retirement date or municipality.',
          'Balance sheet and operating account for the self-employed: depreciation, cash flow, interest, equity.',
          'Wealth dashboards, pillar detail panels and PDF reports on AG Grid and AG Charts.',
        ],
        ai: [
          '<b>Agent instructions and a selective repo memory:</b> only lessons that change how the next agent works, like lead-dev feedback or PR reviews. It is how agents learn in-house libraries no model has seen.',
          '<b>A worktree per agent</b>, with its own environment and database copy, so several agents each take a task through the full cycle, QA included.',
          '<b>A radar:</b> scheduled agents go through the codebase and report findings, each with a plan, to one dashboard. I decide what is worth doing.',
          'Experiments with long-running audits, multi-agent orchestration, evals and observability.',
        ],
        stack: [
          'Next.js',
          'React',
          'NestJS',
          'PostgreSQL',
          'Claude Code',
          'Codex',
          'Nx',
          'TanStack Query',
          'MikroORM',
          'AG Grid',
          'Playwright',
        ],
      },
      {
        when: '01.2023 – 02.2026',
        length: '3 years 2 months',
        city: 'Paris, FR',
        role: 'Full-stack Developer',
        company: 'Zenride',
        link: 'https://www.zenride.co/',
        sector: 'Employee bike leasing',
        summary:
          'A fast-growing start-up with 9 developers. Front and back end of a platform for employees, employers, retailers and the fleet team, with full technical ownership of the Product, Finance and DevOps modules.',
        stats: [
          ['580+', 'pull requests'],
          ['#1', 'of 9 devs for features shipped and support resolved, H1 2025'],
          ['4', 'portals in one app'],
        ],
        built: [
          'A multi-portal web app: employee leasing, retailer checkout, contracts and fleet dashboards.',
          'The fleet management backend: contract lifecycle, payments, insurance and third-party integrations.',
          'Containerised the infrastructure: Docker, Kubernetes and ArgoCD on OVH Cloud, with Sentry and Jest.',
        ],
        ai: [
          '<b>Where I started with AI:</b> GitHub Copilot, then Claude Code with Claude 3.5 Sonnet, and Opus 4 when it came out. Human in the loop: I steered every change and reviewed every line.',
          '<b>My first custom AI rules</b>, for automated AI reviews on pull requests and my everyday agent runs.',
          '<b>AI audits</b> to understand quickly the most sensitive parts of a large codebase and database.',
        ],
        stack: [
          'React',
          'Node',
          'Express',
          'MySQL',
          'Docker',
          'Kubernetes',
          'ArgoCD',
          'React Query',
          'Sequelize',
          'Sentry',
          'Jest',
        ],
      },
      {
        when: '09.2021 – 01.2023',
        length: '1 year 5 months',
        city: 'Lille, FR',
        role: 'Full-stack Developer',
        company: 'Cagette & Paprika',
        link: 'https://cagette-et-paprika.com/',
        sector: 'Grocery home delivery',
        summary:
          'A grocery delivery start-up, acquired by Auchan Retail, now ChronoDrive Livraison. I co-ran technical operations with a senior developer, across the whole product, from the shop to the delivery rounds.',
        stats: [
          ['100s', 'of orders a day'],
          ['5', 'products shipped'],
          ['Auchan', 'acquired the company'],
        ],
        built: [
          'Ported the PHP shop to React and TypeScript, with new features and a better UX.',
          'A React Native shopping app for iOS and Android.',
          'The order management system, and slot allocation for efficient milkman-style delivery rounds.',
          'The Node and PHP backend on OVH, and the original WordPress and WooCommerce site.',
        ],
        stack: [
          'React',
          'React Native',
          'TypeScript',
          'Node',
          'Express',
          'MongoDB',
          'Firebase',
          'MySQL',
          'Redux',
          'Algolia',
          'PHP',
        ],
      },
    ],
    projectsIntro: 'Built for my own use, and open source.',
    projects: [
      {
        name: 'Pomi',
        meta: 'Web · Desktop · iOS · Android · Wear OS',
        body: 'A focus timer that knows what you are focusing on: say a task out loud and AI turns it into a clean task. One codebase for every device, self-hosted.',
        ai: 'Built by scheduled agents: planning runs for features, bugs, performance and security, twice a day. I review every pull request before it merges.',
        stack: 'React · NestJS · PostgreSQL · Tauri · OpenRouter',
        link: 'github.com/Host-It-Labs/pomi',
      },
      {
        name: 'GameHub',
        meta: 'Web · Mobile',
        body: 'Original tabletop games I design and build. Play solo against bots, or with friends from an invite link.',
        ai: 'Agents test every change in a real browser on phone, tablet and desktop; bot-versus-bot simulations check a game’s balance before a rule changes.',
        stack: 'Next.js · React · three.js · Node · SQLite',
        link: 'github.com/Host-It-Labs/gamehub',
      },
      {
        name: 'Vikunja Voice Assistant',
        meta: '2025 · 60+ stars · 200+ installs',
        body: 'Say a task to Home Assistant and AI files it in Vikunja.',
        stack: 'Python · Home Assistant',
        link: 'github.com/NeoHuncho/vikunja-voice-assistant',
      },
      {
        name: 'Open source',
        meta: '2024 – now',
        body: 'Merged pull requests in <a href="https://github.com/go-vikunja/vikunja">Vikunja</a>, <a href="https://github.com/toeverything/AFFiNE">AFFiNE</a> and <a href="https://github.com/home-assistant/brands">Home Assistant</a>.',
        stack: 'Go · Vue · Electron · Python',
      },
      {
        name: 'Brawl Max',
        meta: '2021 – 2022',
        body: 'A React Native companion app for players, published on iOS and Android.',
        stack: 'React Native · Node · GCP · Firebase',
      },
    ],
    skills: [
      [
        'AI engineering',
        'Claude Code · Codex · MCP servers · Agent instructions and repo memory · Scheduled agent runs · Parallel agents in worktrees',
      ],
      [
        'Frontend',
        'TypeScript · React · Next.js · React Native · Tauri · TanStack Query · MUI · AG Grid · Tailwind CSS',
      ],
      [
        'Backend',
        'Node · NestJS · Express · PostgreSQL · MySQL · MongoDB · MikroORM · Sequelize · Redis · Python',
      ],
      [
        'Infra & quality',
        'Docker · Kubernetes · ArgoCD · OVH · GCP · AWS · Firebase · Sentry · Playwright · Jest',
      ],
    ],
    education: [
      {
        when: '09.2018 – 06.2021',
        city: 'Montreal, CA',
        title: 'Bachelor of Business Technology Management',
        school: 'Concordia University, John Molson School of Business',
        detail:
          'Major GPA 3.8 / 4.2. Application development, databases, project management, information systems, IT security and audit.',
      },
      {
        when: '06.2019 – 07.2021',
        city: 'Online',
        title: 'Full Stack Developer certification',
        school: 'freeCodeCamp',
        detail: 'Algorithms, databases, React, and back-end development with Node and Express.',
      },
    ],
    more: [
      [
        'Interests',
        'Mountains and outdoor sport · Hardware and self-hosting on my homelab · Designing tabletop games',
      ],
      ['References', 'Available on request'],
    ],
    footer: 'October 2026',
  },

  fr: {
    lang: 'fr',
    file: 'CV_FR_William_Guinaudie',
    title: 'William Guinaudie · CV',
    role: 'AI Engineer · Développeur Full-stack',
    tagline:
      'Je construis des produits avec des agents IA, et les workflows qui rendent ces agents fiables. Les agents font le gros du travail ; moi je prends les décisions techniques, je relis le code et je livre.',
    facts: [
      ['Lieu', 'Lausanne, Suisse'],
      ['Nationalité', 'Britannique et française'],
      ['Permis', 'Permis de travail suisse'],
      ['Téléphone', '+33 6 35 94 82 91', 'tel:+33635948291'],
      ['E-mail', 'william.guinaudie@gmail.com', 'mailto:william.guinaudie@gmail.com'],
      ['Langues', 'Anglais et français, langues maternelles'],
      ['Portfolio', 'williamguinaudie.com', 'https://www.williamguinaudie.com/?lang=fr'],
      ['GitHub', 'github.com/NeoHuncho', 'https://github.com/NeoHuncho'],
      ['LinkedIn', 'linkedin.com/in/william-g-178156180', 'https://www.linkedin.com/in/william-g-178156180/'],
    ],
    site: 'https://www.williamguinaudie.com/?lang=fr',
    qrCaption: 'La version interactive, avec une maquette jouable de mon board d’agents.',
    how: {
      eyebrow: 'Ma méthode',
      title: 'Les agents font le gros du travail. Je décide.',
      me: 'Moi',
      steps: [
        {
          name: 'Préparer',
          who: 'Agents',
          body: 'Des runs planifiés trient retours et erreurs, ou explorent le code (sécurité, performance). Chaque piste a un plan.',
        },
        { name: 'Décider', who: 'me', body: 'J’accepte, questionne ou rejette chaque plan.' },
        {
          name: 'Construire',
          who: 'Agent + CI',
          body: 'Un agent implémente sur sa propre branche ; la CI vérifie.',
        },
        { name: 'Livrer', who: 'me', body: 'Je relis chaque pull request, puis je merge.' },
      ],
    },
    sections: {
      experience: 'Expérience',
      projects: 'Projets perso',
      skills: 'Outils',
      education: 'Formation',
      more: 'Divers',
    },
    built: 'Ce que j’ai construit',
    ai: 'Comment j’ai utilisé l’IA',
    experience: [
      {
        when: '03.2026 – auj.',
        length: 'Poste actuel',
        city: 'Lausanne, CH',
        role: 'AI Engineer · Développeur Full-stack',
        company: 'Apptitude',
        link: 'https://apptitude.ch/',
        sector: 'Agence digitale',
        summary:
          'Des projets clients, surtout une plateforme suisse de planification financière pour conseillers en patrimoine, du front au back dans un monorepo Nx.',
        stats: [
          ['110+', 'pull requests mergées en 6 mois'],
          ['L’essentiel', 'de l’outillage agents du repo, construit par moi'],
        ],
        built: [
          'Simulation de patrimoine et de retraite sur les trois piliers suisses, avec des actions rapides comme changer de date de retraite ou de commune.',
          'Bilan et compte d’exploitation des indépendants : amortissements, cash-flow, intérêts, fonds propres.',
          'Dashboards patrimoniaux, panneaux de détail par pilier et rapports PDF sur AG Grid et AG Charts.',
        ],
        ai: [
          '<b>Instructions des agents et mémoire sélective du repo :</b> seules les leçons qui changent le travail du prochain agent, comme les retours du lead dev ou les relectures de PR. Les agents y apprennent des librairies maison qu’aucun modèle n’a vues.',
          '<b>Un worktree par agent</b>, avec son environnement et sa copie de la base : plusieurs agents mènent chacun une tâche sur tout le cycle, QA comprise.',
          '<b>Un radar :</b> des agents planifiés passent la codebase en revue et remontent leurs constats, chacun avec un plan, dans un même dashboard. Je décide de ce qui vaut le coup.',
          'Des expérimentations : audits longs, orchestration multi-agents, évaluation et observabilité.',
        ],
        stack: [
          'Next.js',
          'React',
          'NestJS',
          'PostgreSQL',
          'Claude Code',
          'Codex',
          'Nx',
          'TanStack Query',
          'MikroORM',
          'AG Grid',
          'Playwright',
        ],
      },
      {
        when: '01.2023 – 02.2026',
        length: '3 ans 2 mois',
        city: 'Paris, FR',
        role: 'Développeur Full-stack',
        company: 'Zenride',
        link: 'https://www.zenride.co/',
        sector: 'Leasing de vélos salariés',
        summary:
          'Une start-up en forte croissance, 9 développeurs. Front et back d’une plateforme pour salariés, employeurs, magasins et équipe flotte ; responsable technique des modules Produit, Finance et DevOps.',
        stats: [
          ['580+', 'pull requests'],
          ['N° 1', 'sur 9 devs en features livrées et support résolu, S1 2025'],
          ['4', 'portails dans une app'],
        ],
        built: [
          'Une app web multi-portails : leasing salarié, caisse magasin, contrats et dashboards de flotte.',
          'Le backend de gestion de flotte : contrats, paiements, assurances et intégrations tierces.',
          'L’infrastructure conteneurisée : Docker, Kubernetes et ArgoCD sur OVH Cloud, avec Sentry et Jest.',
        ],
        ai: [
          '<b>Mes débuts avec l’IA :</b> GitHub Copilot, puis Claude Code avec Claude 3.5 Sonnet, et Opus 4 à sa sortie. Humain dans la boucle : je pilotais chaque changement et relisais chaque ligne.',
          '<b>Mes premières règles IA maison</b>, pour les relectures IA des pull requests et mes runs d’agents.',
          '<b>Des audits avec l’IA</b> pour comprendre vite les parties sensibles d’une grosse codebase et de sa base.',
        ],
        stack: [
          'React',
          'Node',
          'Express',
          'MySQL',
          'Docker',
          'Kubernetes',
          'ArgoCD',
          'React Query',
          'Sequelize',
          'Sentry',
          'Jest',
        ],
      },
      {
        when: '09.2021 – 01.2023',
        length: '1 an 5 mois',
        city: 'Lille, FR',
        role: 'Développeur Full-stack',
        company: 'Cagette & Paprika',
        link: 'https://cagette-et-paprika.com/',
        sector: 'Livraison de courses à domicile',
        summary:
          'Une start-up de livraison de courses, rachetée par Auchan Retail (aujourd’hui ChronoDrive Livraison). Opérations techniques co-pilotées avec un développeur senior, de la boutique aux tournées.',
        stats: [
          ['Des centaines', 'de commandes par jour'],
          ['5', 'produits livrés'],
          ['Auchan', 'a racheté l’entreprise'],
        ],
        built: [
          'Migration de la boutique PHP vers React et TypeScript, avec de nouvelles features et une meilleure UX.',
          'Une app de courses React Native pour iOS et Android.',
          'La gestion des commandes, et l’allocation de créneaux pour des tournées façon livreur de lait.',
          'Le backend Node et PHP sur OVH, et le site d’origine WordPress et WooCommerce.',
        ],
        stack: [
          'React',
          'React Native',
          'TypeScript',
          'Node',
          'Express',
          'MongoDB',
          'Firebase',
          'MySQL',
          'Redux',
          'Algolia',
          'PHP',
        ],
      },
    ],
    projectsIntro: 'Construits pour mon propre usage, et open source.',
    projects: [
      {
        name: 'Pomi',
        meta: 'Web · Desktop · iOS · Android · Wear OS',
        body: 'Un minuteur de concentration qui sait sur quoi tu te concentres : dis une tâche à voix haute, l’IA la met au propre. Une codebase pour tous les appareils, auto-hébergée.',
        ai: 'Construit par des agents planifiés : features, bugs, performance et sécurité, deux fois par jour. Je relis chaque pull request avant le merge.',
        stack: 'React · NestJS · PostgreSQL · Tauri · OpenRouter',
        link: 'github.com/Host-It-Labs/pomi',
      },
      {
        name: 'GameHub',
        meta: 'Web · Mobile',
        body: 'Des jeux de société originaux, que je conçois et développe. En solo contre des bots, ou entre amis avec un lien d’invitation.',
        ai: 'Des agents testent chaque changement dans un vrai navigateur, sur mobile, tablette et desktop ; des simulations bot contre bot vérifient l’équilibre avant qu’une règle change.',
        stack: 'Next.js · React · three.js · Node · SQLite',
        link: 'github.com/Host-It-Labs/gamehub',
      },
      {
        name: 'Vikunja Voice Assistant',
        meta: '2025 · 60+ étoiles · 200+ installations',
        body: 'Dis une tâche à Home Assistant et l’IA la range dans Vikunja.',
        stack: 'Python · Home Assistant',
        link: 'github.com/NeoHuncho/vikunja-voice-assistant',
      },
      {
        name: 'Open source',
        meta: '2024 – auj.',
        body: 'Des pull requests mergées dans <a href="https://github.com/go-vikunja/vikunja">Vikunja</a>, <a href="https://github.com/toeverything/AFFiNE">AFFiNE</a> et <a href="https://github.com/home-assistant/brands">Home Assistant</a>.',
        stack: 'Go · Vue · Electron · Python',
      },
      {
        name: 'Brawl Max',
        meta: '2021 – 2022',
        body: 'Une app compagnon React Native, publiée sur iOS et Android.',
        stack: 'React Native · Node · GCP · Firebase',
      },
    ],
    skills: [
      [
        'Ingénierie IA',
        'Claude Code · Codex · Serveurs MCP · Instructions et mémoire des agents · Runs planifiés · Agents en parallèle en worktrees',
      ],
      [
        'Frontend',
        'TypeScript · React · Next.js · React Native · Tauri · TanStack Query · MUI · AG Grid · Tailwind CSS',
      ],
      [
        'Backend',
        'Node · NestJS · Express · PostgreSQL · MySQL · MongoDB · MikroORM · Sequelize · Redis · Python',
      ],
      [
        'Infra et qualité',
        'Docker · Kubernetes · ArgoCD · OVH · GCP · AWS · Firebase · Sentry · Playwright · Jest',
      ],
    ],
    education: [
      {
        when: '09.2018 – 06.2021',
        city: 'Montréal, CA',
        title: 'Bachelor of Business Technology Management',
        school: 'Université Concordia, John Molson School of Business',
        detail:
          'Moyenne de majeure 3,8 / 4,2. Développement d’applications, bases de données, gestion de projet, systèmes d’information, sécurité et audit IT.',
      },
      {
        when: '06.2019 – 07.2021',
        city: 'En ligne',
        title: 'Certification Full Stack Developer',
        school: 'freeCodeCamp',
        detail: 'Algorithmique, bases de données, React, et back-end avec Node et Express.',
      },
    ],
    more: [
      [
        'Centres d’intérêt',
        'La montagne et le sport en plein air · Le hardware et l’auto-hébergement · Concevoir des jeux de société',
      ],
      ['Références', 'Sur demande'],
    ],
    footer: 'Octobre 2026',
  },
};
